done but there's some error
ERROR in src/app/service/saving.service.ts:26:54 - error TS2339:
Property 'update' does not exist on type 'AngularFirestoreCollection<unknown>'.

26     this.firestore.collection('Saving/' + saving.id).update(savingObject);
                                                        ~~~~~~
src/app/service/saving.service.ts:52:18 - error TS2339: Property
'dateCreatedTimetamp' does not exist on type 'Saving'.

52           saving.dateCreatedTimetamp = new Date(saving.dateCreated);
                    ~~~~~~~~~~~~~~~~~~~
src/app/saving-list/saving-list.component.ts:22:3 - error TS2300: Duplicate identifier 'saving'.

22   saving: Saving[];
     ~~~~~~
src/app/saving-list/saving-list.component.ts:22:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'saving' must be of type 'Saving', but here has type 'Saving[]'.

22   saving: Saving[];
     ~~~~~~

  src/app/saving-list/saving-list.component.ts:19:3
    19   saving: Saving = new Saving();
         ~~~~~~
    'saving' was also declared here.
src/app/saving-list/saving-list.component.ts:34:7 - error TS2739: Type 'Saving[]' is missing the following properties from type 'Saving': id, name, saving, info, dateCreated

34       this.saving = data.map(e => {
         ~~~~~~~~~~~
src/app/saving-list/saving-list.component.ts:37:11 - error TS2698: Spread types may only be created from object types.

37           ...e.payload.doc.data()
             ~~~~~~~~~~~~~~~~~~~~~~~
src/app/saving-list/saving-list.component.ts:71:7 - error TS2322: Type 'Saving[]' is not assignable to type 'Saving'.

71       this.saving = data.map(e => {
         ~~~~~~~~~~~
src/app/saving-list/saving-list.component.ts:74:11 - error TS2698: Spread types may only be created from object types.

74           ...e.payload.doc.data()
             ~~~~~~~~~~~~~~~~~~~~~~~
src/app/saving-list/saving-list.component.ts:82:5 - error TS2739: Type 'undefined[]' is missing the following properties from type 'Saving': id, name, saving, info, dateCreated

82     this.saving = [];
       ~~~~~~~~~~~